vida = 3;
game_over_ativado = false;
fade_audio_gameover = false;
yspeed=3;
xspeed=6;
right=false;
up=false;
moving=false;
segurando_vela = false;  // Se o jogador está segurando a vela
vela_segurada = noone;   // Referência para a vela que está segurando
distancia_interacao = 50; 
pode_interagir = true;  // Impede de pegar e soltar no mesmo frame
vela_no_chao = true;
pode_apertar_E = true;  // TRAVA para não executar duas vezes
segurando_key = false;
offset_letterf_x = 0;
offset_letterf_y = -60;
offset_lettere_x = 0;
offset_lettere_y = -200;
vida = 3;
invencivel = false;
tempo_invencivel = room_speed * 2; // 3 segundos de escudo
var nova_instancia = instance_create_layer(0, 0, "Instances", obj_roomsla);
nova_instancia.image_xscale = 7;
nova_instancia.image_yscale = 7;
alarme_candle_ativado = false;
segurando_velatemp = false;
portahallway = false;
portatempcandle = false;
vela_ja_derreteu = false;
alarme_candletemp_ativado = false;
candletemp_ja_derreteu = false;
game_over_ativado = false;
fade_audio_gameover = false;
som_passos = -1;
som_ghost1 = -1;
som_candlefire = -1;
som_defaultmusic = -1;
som_corridormusic = -1;
som_gameover = -1;
musica_pos_gameover_tocada = false;
estava_seg_vela = false;
estava_seg_velatemp = false;